### ISSUE TITLE
big number out of range?

### ISSUE THREAD

**Issue by samrock5000** [rkalis/cashscript-playground#6]
I ran into this error while using  v0.6.5 on the XEC/ecash network with the Escrow contract

![photo_2022-08-09 15 00 58](https://user-images.githubusercontent.com/35318078/183750165-ec8d595f-4d39-47c2-ba5f-aa91711309ce.jpeg)

I was able to successfully broadcast the same transaction with ts-node, which leads me to believe this is an issue with the web version.

I haven't had any issues with smaller tx amounts while using the playground with the same contract, its been working great with amounts < 1,000,000 satoshis.

**Comment by mr-zwets** [comment]
This is because XEC has not had the 64-bit integer upgrade, unlike BCH.
So you'll only be able to make smart contracts containing ~ 21,000,000 sats.
You might be able to work around this issue with complex truncation but XEC has not focused on smart contracts unlike BCH.

I think this issue can be closed.
